#!/bin/bash
if [ $# == "0" ]; then
	for test in $(ls | grep .in | sed -e s/'\.in'//)
	do
		reset
		./vt $test
		read none
	done	
fi

if [ -e "$1.in" ]; then
	echo "Test #$1:"
        echo "------------------------"
	cat $1.in
	echo "------------------------"
	echo ""
	echo "Answer #$1:"
	echo "------------------------"
	cat $1.a
	echo "------------------------"
	if [ -e $1.a.gif ]; then 
		if [ $(stat -c%s "$1.a.gif") != "59" ]; then
			echo "Opening image..." && gnome-open $1.a.gif && echo "Image succesfully opened"
		else
			echo "Image is empty"
		fi
	else
		echo "Image doesn't exists"
	fi
fi
